In [1]:
import xlwings as xw

In [2]:
wb = xw.Book("hello.xlsm")

In [3]:
sheet = wb.sheets[0]

In [4]:
data = sheet.range("A8:A10").value
data

[1.0, 3.0, 5.0]

In [5]:
sum(data)

9.0

In [6]:
data = sheet.range("A8:B8").value
data

[1.0, 2.0]

In [7]:
sum(data)

3.0

In [8]:
data = sheet.range("A8:B10").value
data

[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]

In [9]:
sum(data)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [10]:
data = sheet.range("A8").value
data

1.0

In [11]:
sum(data)

TypeError: 'float' object is not iterable

In [12]:
sheet.range("A8:A10").options(ndim = 2).value

[[1.0], [3.0], [5.0]]

In [13]:
sheet.range("A8:B10").options(ndim = 2).value

[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]

In [14]:
sheet.range("A8").options(ndim = 2).value

[[1.0]]

In [15]:
import numpy as np

In [16]:
data = sheet.range("A8:A10").options(np.array).value
data

array([1., 3., 5.])

In [17]:
data.sum()

9.0

In [18]:
data = sheet.range("A8:B10").options(np.array).value
data

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [19]:
data.sum()

21.0

In [20]:
data = sheet.range("A8").options(np.array, ndim = 2).value
data

array([[1.]])

In [21]:
data.sum()

1.0

In [22]:
def randomnumb(mean, std, rows, columns):
    return np.random.normal(mean, std, 
                            (int(rows), int(columns)))

In [23]:
data = randomnumb(10, 2, 5, 4)
data

array([[10.58118161,  8.20122055, 10.36483332, 11.78394509],
       [10.44663343, 12.49005693,  6.9394798 ,  8.92344649],
       [ 8.71442858, 10.77413689,  9.01729555,  9.54279205],
       [10.77186038, 11.99747595, 11.12573289,  9.9746666 ],
       [ 6.4627709 , 10.14310773, 10.06579468,  8.21130525]])

In [24]:
import pandas as pd

In [25]:
sheet.range("C16:F20").options(pd.DataFrame, 
                               index = False, header = False).value

0          1          2          3
0  26.409121  14.726827  18.177919  20.074012
1  20.288585  19.134917   9.236178  11.598370
2  22.770481  22.639953  19.321789  16.199448
3  23.729441  17.639307  27.641832  19.709210
4  23.899103  18.427364  16.292729  30.683519

In [26]:
sheet.range("C16").options(pd.DataFrame, 
                    expand = "table", index = False, header = False).value

0          1          2          3
0  26.409121  14.726827  18.177919  20.074012
1  20.288585  19.134917   9.236178  11.598370
2  22.770481  22.639953  19.321789  16.199448
3  23.729441  17.639307  27.641832  19.709210
4  23.899103  18.427364  16.292729  30.683519

In [27]:
df = sheet.range("C16").options(pd.DataFrame, 
                    expand = "table", index = False, header = False).value
df

0          1          2          3
0  26.409121  14.726827  18.177919  20.074012
1  20.288585  19.134917   9.236178  11.598370
2  22.770481  22.639953  19.321789  16.199448
3  23.729441  17.639307  27.641832  19.709210
4  23.899103  18.427364  16.292729  30.683519

In [28]:
df.sum()#.sum()

0    117.096732
1     92.568368
2     90.670448
3     98.264558
dtype: float64

In [29]:
df.sum().sum()

398.6001062119084

In [30]:
df.add(1)

0          1          2          3
0  27.409121  15.726827  19.177919  21.074012
1  21.288585  20.134917  10.236178  12.598370
2  23.770481  23.639953  20.321789  17.199448
3  24.729441  18.639307  28.641832  20.709210
4  24.899103  19.427364  17.292729  31.683519